<a href="https://colab.research.google.com/github/UjanGanguli/Python-Basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Topic:  Numpy

1.Create a array using numpy for 10 barcodes of injection

In [ ]:
import numpy as np
arr1=np.random.randn(10)
arr1

array([ 0.35499849, -0.6288824 , -0.76250343, -0.42068325,  1.05763877,
        0.27375956,  1.39472354,  1.66868481, -0.99992322,  0.70291968])

2.Create a 2 different array and number 1 for dolo ,2 for crocine and so on(both arrays have different datatypes)

In [ ]:
arr2=np.array(['dolo','crocine','Paracetamol','azithromicine','pan-d'])
arr3=np.array([1,2,3,4,5])
print(arr2)
print(arr3)

['dolo' 'crocine' 'Paracetamol' 'azithromicine' 'pan-d']
[1 2 3 4 5]


3.Create a array using numpy with zero alotted for all entries

In [ ]:
s=np.zeros(5)
s

array([0., 0., 0., 0., 0.])

4.Increase the assigned value by 1.

In [ ]:
s[1]=1
s

array([0., 1., 0., 0., 0.])

5.Create a 2D array which has medical code,medicine code,medicine quantity,price.

In [ ]:
main=np.array([[1,2,5,25],[44,5,10,2000],[8,1,10,200]])
main

array([[   1,    2,    5,   25],
       [  44,    5,   10, 2000],
       [   8,    1,   10,  200]])

6.Get the shape of the above 2D array.

In [ ]:
main.shape

(3, 4)

7.Get the datatype of the 2 arrays created in 2nd question

In [ ]:
print(arr2.dtype)
print(arr3.dtype)

<U13
int64


8.Create a simple 3D array with particular medical details in regard with the medicine.

In [ ]:
main1=([[[1,2,5,25],[1,1,5,1000]],[[8,1,10,200],[8,5,6,8000]],[[44,5,10,2000],[44,1,10,28]]])
main1

[[[1, 2, 5, 25], [1, 1, 5, 1000]],
 [[8, 1, 10, 200], [8, 5, 6, 8000]],
 [[44, 5, 10, 2000], [44, 1, 10, 28]]]

9.Find the dot product of the 2D matrix with the quantity available thereby finding the final worth of the medicines available.

In [ ]:
a=np.dot(main[0,3],5)
print("the worth of stock available in store 1 is:",a)

the worth of stock available in store 1 is: 125


10.Increase all vales of "Main array " by 1 using matrix addition

In [ ]:
b=main+([1,1,1,1])
b

array([[   2,    3,    6,   26],
       [  45,    6,   11, 2001],
       [   9,    2,   11,  201]])

11.Print the first, third, and last position of any random Matrix

In [ ]:
num = np.array([0, 65, 100, 125, 2550, 2025])

print('first position:',num[0])
print('third position:',num[2])
print('third position:',num[-1])

first position: 0
third position: 100
third position: 2025


12.print even entries of  a array

In [ ]:
import numpy as np
x = np.array([2, 3, 7, 11, 13, 17, 19, 23, 29, 31, 37])
print(x[0:11:2])

[ 2  7 13 19 29 37]


13.Array of all the even integers from 30 to 100

In [ ]:
import numpy as np
array=np.arange(30,102,2)

print(array)

[ 30  32  34  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64
  66  68  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


14.reverse the array

In [ ]:
arr = np.array([1, 2, 4, 5, 6])

reverse_arr = np.flipud(arr)
print(reverse_arr)

[6 5 4 2 1]


15.Arrange the 2D array from 5th question based on increasing values .

In [ ]:
c=np.array([[1,2,5,25],[44,5,10,2000],[8,1,10,200]])
print(np.sort(c))

[[   1    2    5   25]
 [   5   10   44 2000]
 [   1    8   10  200]]


16.Make a transpose of a array.

In [ ]:
arr1=np.arange(20).reshape(4,5)
arr=np.array([[2,5,6,7],[8,9,56,7]])
arr.T
arr1.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

17.Dot product of two matrices.

In [ ]:
arr=np.random.randn(6,3)
np.dot(arr.T,arr)

array([[ 4.24048421, -2.5243562 ,  0.8441783 ],
       [-2.5243562 , 15.12975161,  0.254698  ],
       [ 0.8441783 ,  0.254698  ,  2.19623741]])

18.Make an array of zeroes

In [ ]:
a=np.zeros(10)
print(a)
b=np.zeros((3,6))
print(b)
c=np.empty((2,3,2))
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[4.94e-324 9.88e-324]
  [2.47e-323 1.24e-322]
  [2.47e-323 4.94e-323]]

 [[2.17e-322 9.88e-321]
  [4.94e-324 3.95e-323]
  [4.94e-323 9.88e-322]]]


19.Indexing of an array(print 12 from index 5 to 8)

In [ ]:
arr4=np.arange(10) #indexing
print(arr4)
arr4[5:8]=12
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12  8  9]


20.Delete arr4

In [ ]:
del(arr4)
print(arr4)

NameError: ignored